In [48]:
import pandas as pd

In [131]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from datetime import datetime
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [50]:
df = pd.read_csv("/Users/gouribenni/COURSES SEM 2/GWAR/PROJECTS/cleaned_supply_chain.csv")

In [51]:
df

,Type,Delivery_Status,Customer_City,Customer_Country,Customer_Segment,Customer_State,Customer_Street,Department_Name,Market,Order_City,...,Order_Item_Discount,Order_Item_Discount_Rate,Order_Item_Product_Price,Order_Item_Profit_Ratio,Sales,Order_Item_Total,Order_Profit_Per_Order,Product_Price,order_date,shipping_date
0,DEBIT,Advance shipping,Caguas,Puerto Rico,Consumer,PR,5365 Noble Nectar Island,Fitness,Pacific Asia,Bekasi,...,13.110000,0.04,327.750000,0.29,327.750000,314.640015,91.250000,327.750000,1/31/2018,2/3/2018
1,TRANSFER,Late delivery,Caguas,Puerto Rico,Consumer,PR,2679 Rustic Loop,Fitness,Pacific Asia,Bikaner,...,16.389999,0.05,327.750000,-0.80,327.750000,311.359985,-249.089996,327.750000,1/13/2018,1/18/2018
2,CASH,Shipping on time,San Jose,EE. UU.,Consumer,CA,8510 Round Bear Gate,Fitness,Pacific Asia,Bikaner,...,18.030001,0.06,327.750000,-0.80,327.750000,309.720001,-247.779999,327.750000,1/13/2018,1/17/2018
3,DEBIT,Advance shipping,Los Angeles,EE. UU.,Home Office,CA,3200 Amber Bend,Fitness,Pacific Asia,Townsville,...,22.940001,0.07,327.750000,0.08,327.750000,304.809998,22.860001,327.750000,1/13/2018,1/16/2018
4,PAYMENT,Advance shipping,Caguas,Puerto Rico,Corporate,PR,8671 Iron Anchor Corners,Fitness,Pacific Asia,Townsville,...,29.500000,0.09,327.750000,0.45,327.750000,298.250000,134.210007,327.750000,1/13/2018,1/15/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,Shipping on time,Brooklyn,EE. UU.,Home Office,NY,1322 Broad Glade,Fan Shop,Pacific Asia,Shangh√°i,...,0.000000,0.00,399.980011,0.10,399.980011,399.980011,40.000000,399.980011,1/16/2016,1/20/2016
180515,DEBIT,Late delivery,Bakersfield,EE. UU.,Corporate,CA,7330 Broad Apple Moor,Fan Shop,Pacific Asia,Hirakata,...,4.000000,0.01,399.980011,-1.55,399.980011,395.980011,-613.770019,399.980011,1/16/2016,1/19/2016
180516,TRANSFER,Late delivery,Bristol,EE. UU.,Corporate,CT,97 Burning Landing,Fan Shop,Pacific Asia,Adelaide,...,8.000000,0.02,399.980011,0.36,399.980011,391.980011,141.110001,399.980011,1/15/2016,1/20/2016
180517,PAYMENT,Advance shipping,Caguas,Puerto Rico,Consumer,PR,2585 Silent Autumn Landing,Fan Shop,Pacific Asia,Adelaide,...,12.000000,0.03,399.980011,0.48,399.980011,387.980011,186.229996,399.980011,1/15/2016,1/18/2016
180518,PAYMENT,Shipping on time,Caguas,Puerto Rico,Consumer,PR,697 Little Meadow,Fan Shop,Pacific Asia,Nagercoil,...,16.000000,0.04,399.980011,0.44,399.980011,383.980011,168.949997,399.980011,1/15/2016,1/19/2016

In [52]:
df = pd.get_dummies(df, columns=['Delivery_Status'], prefix='Delivery_Status')

In [53]:
df

,Type,Customer_City,Customer_Country,Customer_Segment,Customer_State,Customer_Street,Department_Name,Market,Order_City,Order_Country,...,Sales,Order_Item_Total,Order_Profit_Per_Order,Product_Price,order_date,shipping_date,Delivery_Status_Advance shipping,Delivery_Status_Late delivery,Delivery_Status_Shipping canceled,Delivery_Status_Shipping on time
0,DEBIT,Caguas,Puerto Rico,Consumer,PR,5365 Noble Nectar Island,Fitness,Pacific Asia,Bekasi,Indonesia,...,327.750000,314.640015,91.250000,327.750000,1/31/2018,2/3/2018,1,0,0,0
1,TRANSFER,Caguas,Puerto Rico,Consumer,PR,2679 Rustic Loop,Fitness,Pacific Asia,Bikaner,India,...,327.750000,311.359985,-249.089996,327.750000,1/13/2018,1/18/2018,0,1,0,0
2,CASH,San Jose,EE. UU.,Consumer,CA,8510 Round Bear Gate,Fitness,Pacific Asia,Bikaner,India,...,327.750000,309.720001,-247.779999,327.750000,1/13/2018,1/17/2018,0,0,0,1
3,DEBIT,Los Angeles,EE. UU.,Home Office,CA,3200 Amber Bend,Fitness,Pacific Asia,Townsville,Australia,...,327.750000,304.809998,22.860001,327.750000,1/13/2018,1/16/2018,1,0,0,0
4,PAYMENT,Caguas,Puerto Rico,Corporate,PR,8671 Iron Anchor Corners,Fitness,Pacific Asia,Townsville,Australia,...,327.750000,298.250000,134.210007,327.750000,1/13/2018,1/15/2018,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,Brooklyn,EE. UU.,Home Office,NY,1322 Broad Glade,Fan Shop,Pacific Asia,Shangh√°i,China,...,399.980011,399.980011,40.000000,399.980011,1/16/2016,1/20/2016,0,0,0,1
180515,DEBIT,Bakersfield,EE. UU.,Corporate,CA,7330 Broad Apple Moor,Fan Shop,Pacific Asia,Hirakata,Jap√≥n,...,399.980011,395.980011,-613.770019,399.980011,1/16/2016,1/19/2016,0,1,0,0
180516,TRANSFER,Bristol,EE. UU.,Corporate,CT,97 Burning Landing,Fan Shop,Pacific Asia,Adelaide,Australia,...,399.980011,391.980011,141.110001,399.980011,1/15/2016,1/20/2016,0,1,0,0
180517,PAYMENT,Caguas,Puerto Rico,Consumer,PR,2585 Silent Autumn Landing,Fan Shop,Pacific Asia,Adelaide,Australia,...,399.980011,387.980011,186.229996,399.980011,1/15/2016,1/18/2016,1,0,0,0
180518,PAYMENT,Caguas,Puerto Rico,Consumer,PR,697 Little Meadow,Fan Shop,Pacific Asia,Nagercoil,India,...,399.980011,383.980011,168.949997,399.980011,1/15/2016,1/19/2016,0,0,0,1

In [54]:
df = pd.get_dummies(df, columns=['Type'], prefix='Type')

In [55]:
df

,Customer_City,Customer_Country,Customer_Segment,Customer_State,Customer_Street,Department_Name,Market,Order_City,Order_Country,Order_Region,...,order_date,shipping_date,Delivery_Status_Advance shipping,Delivery_Status_Late delivery,Delivery_Status_Shipping canceled,Delivery_Status_Shipping on time,Type_CASH,Type_DEBIT,Type_PAYMENT,Type_TRANSFER
0,Caguas,Puerto Rico,Consumer,PR,5365 Noble Nectar Island,Fitness,Pacific Asia,Bekasi,Indonesia,Southeast Asia,...,1/31/2018,2/3/2018,1,0,0,0,0,1,0,0
1,Caguas,Puerto Rico,Consumer,PR,2679 Rustic Loop,Fitness,Pacific Asia,Bikaner,India,South Asia,...,1/13/2018,1/18/2018,0,1,0,0,0,0,0,1
2,San Jose,EE. UU.,Consumer,CA,8510 Round Bear Gate,Fitness,Pacific Asia,Bikaner,India,South Asia,...,1/13/2018,1/17/2018,0,0,0,1,1,0,0,0
3,Los Angeles,EE. UU.,Home Office,CA,3200 Amber Bend,Fitness,Pacific Asia,Townsville,Australia,Oceania,...,1/13/2018,1/16/2018,1,0,0,0,0,1,0,0
4,Caguas,Puerto Rico,Corporate,PR,8671 Iron Anchor Corners,Fitness,Pacific Asia,Townsville,Australia,Oceania,...,1/13/2018,1/15/2018,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,Home Office,NY,1322 Broad Glade,Fan Shop,Pacific Asia,Shangh√°i,China,Eastern Asia,...,1/16/2016,1/20/2016,0,0,0,1,1,0,0,0
180515,Bakersfield,EE. UU.,Corporate,CA,7330 Broad Apple Moor,Fan Shop,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,...,1/16/2016,1/19/2016,0,1,0,0,0,1,0,0
180516,Bristol,EE. UU.,Corporate,CT,97 Burning Landing,Fan Shop,Pacific Asia,Adelaide,Australia,Oceania,...,1/15/2016,1/20/2016,0,1,0,0,0,0,0,1
180517,Caguas,Puerto Rico,Consumer,PR,2585 Silent Autumn Landing,Fan Shop,Pacific Asia,Adelaide,Australia,Oceania,...,1/15/2016,1/18/2016,1,0,0,0,0,0,1,0
180518,Caguas,Puerto Rico,Consumer,PR,697 Little Meadow,Fan Shop,Pacific Asia,Nagercoil,India,South Asia,...,1/15/2016,1/19/2016,0,0,0,1,0,0,1,0

In [56]:
df = pd.get_dummies(df, columns=['Customer_Segment'], prefix='Customer_Segment')

In [57]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Department_Name,Market,Order_City,Order_Country,Order_Region,Order_State,...,Delivery_Status_Late delivery,Delivery_Status_Shipping canceled,Delivery_Status_Shipping on time,Type_CASH,Type_DEBIT,Type_PAYMENT,Type_TRANSFER,Customer_Segment_Consumer,Customer_Segment_Corporate,Customer_Segment_Home Office
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Fitness,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,...,0,0,0,0,1,0,0,1,0,0
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Fitness,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,...,1,0,0,0,0,0,1,1,0,0
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Fitness,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,...,0,0,1,1,0,0,0,1,0,0
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Fitness,Pacific Asia,Townsville,Australia,Oceania,Queensland,...,0,0,0,0,1,0,0,0,0,1
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Fitness,Pacific Asia,Townsville,Australia,Oceania,Queensland,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Fan Shop,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,...,0,0,1,1,0,0,0,0,0,1
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Fan Shop,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,...,1,0,0,0,1,0,0,0,1,0
180516,Bristol,EE. UU.,CT,97 Burning Landing,Fan Shop,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,...,1,0,0,0,0,0,1,0,1,0
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Fan Shop,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,...,0,0,0,0,0,1,0,1,0,0
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Fan Shop,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,...,0,0,1,0,0,1,0,1,0,0

In [58]:
df = pd.get_dummies(df, columns=['Department_Name'], prefix='Department_Name')

In [59]:
df = pd.get_dummies(df, columns=['Order_Status'], prefix='Order_Status')

In [60]:
df = pd.get_dummies(df, columns=['Product_Name'], prefix='Product_Name')

In [61]:
df = pd.get_dummies(df, columns=['Shipping_Mode'], prefix='Shipping_Mode')

In [62]:
df = pd.get_dummies(df, columns=['Category_Name'], prefix='Category_Name')

In [64]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,...,Category_Name_Sporting Goods,Category_Name_Strength Training,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,...,1,0,0,0,0,0,0,0,0,0
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,1,0,0,0,0,0,0,0,0,0
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,1,0,0,0,0,0,0,0,0,0
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,1,0,0,0,0,0,0,0,0,0
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,...,0,0,0,0,0,0,0,0,0,0
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,...,0,0,0,0,0,0,0,0,0,0
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,0,0
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,0,0
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,...,0,0,0,0,0,0,0,0,0,0

In [65]:
sales_scaler = MinMaxScaler(feature_range=(0, 1))

In [66]:
df[num_cols] = sales_scaler.fit_transform(df[num_cols])

In [67]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,...,Category_Name_Sporting Goods,Category_Name_Strength Training,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,...,1,0,0,0,0,0,0,0,0,0
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,1,0,0,0,0,0,0,0,0,0
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,1,0,0,0,0,0,0,0,0,0
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,1,0,0,0,0,0,0,0,0,0
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,...,0,0,0,0,0,0,0,0,0,0
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,...,0,0,0,0,0,0,0,0,0,0
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,0,0
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,0,0
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,...,0,0,0,0,0,0,0,0,0,0

In [69]:
df["shipping_date"] = pd.to_datetime(df["shipping_date"], format="%m/%d/%Y")

In [73]:
df["day_of_week_shipping"] = df["shipping_date"].dt.day_name()

In [74]:
print(df[["shipping_date", "day_of_week_shipping"]])

       shipping_date day_of_week_shipping
0         2018-02-03             Saturday
1         2018-01-18             Thursday
2         2018-01-17            Wednesday
3         2018-01-16              Tuesday
4         2018-01-15               Monday
...              ...                  ...
180514    2016-01-20            Wednesday
180515    2016-01-19              Tuesday
180516    2016-01-20            Wednesday
180517    2016-01-18               Monday
180518    2016-01-19              Tuesday

[180519 rows x 2 columns]

In [75]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,...,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs,day_of_week,day_of_week_shipping
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,...,0,0,0,0,0,0,0,0,Saturday,Saturday
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,0,Thursday,Thursday
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,0,Monday,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,Monday,Monday
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday

In [76]:
df["order_date"] = pd.to_datetime(df["order_date"], format="%m/%d/%Y")

In [77]:
df["day_of_week_order"] = df["order_date"].dt.day_name()

In [78]:
print(df[["order_date", "day_of_week_order"]])

       order_date day_of_week_order
0      2018-01-31          Saturday
1      2018-01-13          Thursday
2      2018-01-13         Wednesday
3      2018-01-13           Tuesday
4      2018-01-13            Monday
...           ...               ...
180514 2016-01-16         Wednesday
180515 2016-01-16           Tuesday
180516 2016-01-15         Wednesday
180517 2016-01-15            Monday
180518 2016-01-15           Tuesday

[180519 rows x 2 columns]

In [79]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,...,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs,day_of_week,day_of_week_shipping,day_of_week_order
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,...,0,0,0,0,0,0,0,Saturday,Saturday,Saturday
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,Thursday,Thursday,Thursday
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,Wednesday,Wednesday,Wednesday
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,Tuesday,Tuesday,Tuesday
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,Monday,Monday,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,...,0,0,0,0,0,0,0,Wednesday,Wednesday,Wednesday
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,...,0,0,0,0,0,0,0,Tuesday,Tuesday,Tuesday
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,Wednesday,Wednesday,Wednesday
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,Monday,Monday,Monday
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,...,0,0,0,0,0,0,0,Tuesday,Tuesday,Tuesday

In [80]:
df.drop('day_of_week', axis = 1, inplace = True)

In [81]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,...,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs,day_of_week_shipping,day_of_week_order
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,...,0,0,0,0,0,0,0,0,Saturday,Saturday
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,0,Thursday,Thursday
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,...,0,0,0,0,0,0,0,0,Monday,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,Wednesday,Wednesday
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,...,0,0,0,0,0,0,0,0,Monday,Monday
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,...,0,0,0,0,0,0,0,0,Tuesday,Tuesday

In [97]:
df.to_csv('/Users/gouribenni/Downloads/Feature_eng.csv', index=False, sep='\t')

In [98]:
df['Delivery_Delay'] = df['Days_for_shipment_(scheduled)'] - df['Days_for_shipping_(real)']

In [99]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,Customer_Id,Department_Id,Order_Customer_Id,Order_Id,Order_Item_Cardprod_Id,Order_Item_Id,Product_Card_Id,Product_Category_Id,Days_for_shipping_(real),Days_for_shipment_(scheduled),Late_delivery_risk,Order_Item_Quantity,Benefit_per_order,Sales_per_customer,Latitude,Longitude,Order_Item_Discount,Order_Item_Discount_Rate,Order_Item_Product_Price,Order_Item_Profit_Ratio,Sales,Order_Item_Total,Order_Profit_Per_Order,Product_Price,order_date,shipping_date,Delivery_Status_Advance shipping,Delivery_Status_Late delivery,Delivery_Status_Shipping canceled,Delivery_Status_Shipping on time,Type_CASH,Type_DEBIT,Type_PAYMENT,Type_TRANSFER,Customer_Segment_Consumer,Customer_Segment_Corporate,Customer_Segment_Home Office,Department_Name_Apparel,Department_Name_Book Shop,Department_Name_Discs Shop,Department_Name_Fan Shop,Department_Name_Fitness,Department_Name_Footwear,Department_Name_Golf,Department_Name_Health and Beauty,Department_Name_Outdoors,Department_Name_Pet Shop,Department_Name_Technology,Order_Status_CANCELED,Order_Status_CLOSED,Order_Status_COMPLETE,Order_Status_ON_HOLD,Order_Status_PAYMENT_REVIEW,Order_Status_PENDING,Order_Status_PENDING_PAYMENT,Order_Status_PROCESSING,Order_Status_SUSPECTED_FRAUD,Product_Name_Adult dog supplies,Product_Name_Baby sweater,Product_Name_Bag Boy Beverage Holder,Product_Name_Bag Boy M330 Push Cart,Product_Name_Bowflex SelectTech 1090 Dumbbells,Product_Name_Bridgestone e6 Straight Distance NFL Carolina,Product_Name_Bridgestone e6 Straight Distance NFL San Dieg,Product_Name_Bridgestone e6 Straight Distance NFL Tennesse,Product_Name_Brooks Women's Ghost 6 Running Shoe,Product_Name_Bushnell Pro X7 Jolt Slope Rangefinder,Product_Name_CDs of rock,Product_Name_Children's heaters,Product_Name_Cleveland Golf Collegiate My Custom Wedge 588,Product_Name_Cleveland Golf Women's 588 RTX CB Satin Chrom,Product_Name_Clicgear 8.0 Shoe Brush,Product_Name_Clicgear Rovic Cooler Bag,Product_Name_Columbia Men's PFG Anchor Tough T-Shirt,Product_Name_DVDs,Product_Name_Dell Laptop,Product_Name_Diamondback Boys' Insight 24 Performance Hybr,Product_Name_Diamondback Girls' Clarity 24 Hybrid Bike 201,Product_Name_Diamondback Women's Serene Classic Comfort Bi,Product_Name_ENO Atlas Hammock Straps,Product_Name_Elevation Training Mask 2.0,Product_Name_Field & Stream Sportsman 16 Gun Fire Safe,Product_Name_Fighting video games,Product_Name_First aid kit,Product_Name_Fitbit The One Wireless Activity & Sleep Trac,Product_Name_Garmin Approach S3 Golf GPS Watch,Product_Name_Garmin Approach S4 Golf GPS Watch,Product_Name_Garmin Forerunner 910XT GPS Watch,Product_Name_Glove It Imperial Golf Towel,Product_Name_Glove It Urban Brick Golf Towel,Product_Name_Glove It Women's Imperial Golf Glove,Product_Name_Glove It Women's Mod Oval 3-Zip Carry All Gol,Product_Name_Glove It Women's Mod Oval Golf Glove,Product_Name_GoPro HERO3+ Black Edition Camera,Product_Name_GolfBuddy VT3 GPS Watch,Product_Name_Hirzl Men's Hybrid Golf Glove,Product_Name_Hirzl Women's Hybrid Golf Glove,Product_Name_Hirzl Women's Soffft Flex Golf Glove,Product_Name_Industrial consumer electronics,Product_Name_LIJA Women's Argyle Golf Polo,Product_Name_LIJA Women's Button Golf Dress,Product_Name_LIJA Women's Eyelet Sleeveless Golf Polo,Product_Name_LIJA Women's Mid-Length Panel Golf Shorts,Product_Name_Lawn mower,Product_Name_MDGolf Pittsburgh Penguins Putter,Product_Name_Men's gala suit,Product_Name_Merrell Men's All Out Flash Trail Running Sho,Product_Name_Merrell Women's Grassbow Sport Hiking Shoe,Product_Name_Merrell Women's Grassbow Sport Waterproof Hik,Product_Name_Merrell Women's Siren Mid Waterproof Hiking B,Product_Name_Mio ALPHA Heart Rate Monitor/Sport Watch,Product_Name_Nike Dri-FIT Crew Sock 6 Pack,Product_Name_Nike Kids' Grade School KD VI Basketball Shoe,Product_Name_Nike Men's CJ Elite 2 TD Football Cleat,Product_Name_Nike Men's Comfort 2 Slide,Product_Name_Nike Men's Deutschland Weltmeister Winners Bl,Product_Name_Nike Men's Dri-FIT Victory Golf Polo,Product_Name_Nike Men's Fingertrap Max Training Shoe,Product_Name_Nike Men's Free 5.0+ Running Shoe,Product_Name_Nike Men's Free TR 5.0 TB Training Shoe,Product_Name_Nike Men's Kobe IX Elite Low Basketball Shoe,Product_Name_Nike Women's Free 5.0 TR FIT PRT 4 Training S,Product_Name_Nike Women's Legend V-Neck T-Shirt,Product_Name_Nike Women's Tempo Shorts,Product_Name_O'Brien Men's Neoprene Life Vest,Product_Name_Ogio Race Golf Shoes,Product_Name_Pelican Maverick 100X Kayak,Product_Name_Pelican Sunstream 100 Kayak,Product_Name_Perfect Fitness Perfect Rip Deck,Product_Name_Polar FT4 Heart Rate Monitor,Product_Name_Polar Loop Activity Tracker,Product_Name_Porcelain crafts,Product_Name_Rock music,Product_Name_SOLE E25 Elliptical,Product_Name_SOLE E35 Elliptical,Product_Name_Smart watch,Product_Name_Sports Books,Product_Name_Stiga Master Series ST3100 Competition Indoor,Product_Name_Summer dresses,Product_Name_TYR Boys' Team Digi Jammer,Product_Name_TaylorMade 2014 Purelite Stand Bag,Product_Name_TaylorMade White Smoke IN-12 Putter,Product_Name_TaylorMade Women's RBZ SL Rescue,Product_Name_Team Golf New England Patriots Putter Grip,Product_Name_Team Golf Pittsburgh Steelers Putter Grip,Product_Name_Team Golf San Francisco Giants Putter Grip,Product_Name_Team Golf St. Louis Cardinals Putter Grip,Product_Name_Team Golf Tennessee Volunteers Putter Grip,Product_Name_Team Golf Texas Longhorns Putter Grip,Product_Name_The North Face Women's Recon Backpack,Product_Name_Titleist Club Glove Travel Cover,Product_Name_Titleist Pro V1 High Numbers Personalized Gol,Product_Name_Titleist Pro V1x Golf Balls,Product_Name_Titleist Pro V1x High Numbers Golf Balls,Product_Name_Titleist Pro V1x High Numbers Personalized Go,Product_Name_Titleist Small Wheeled Travel Cover,Product_Name_Top Flite Women's 2014 XL Hybrid,Product_Name_Total Gym 1400,Product_Name_Toys,Product_Name_Under Armour Girls' Toddler Spine Surge Runni,Product_Name_Under Armour Hustle Storm Medium Duffle Bag,Product_Name_Under Armour Kids' Mercenary Slide,Product_Name_Under Armour Men's Compression EV SL Slide,Product_Name_Under Armour Men's Tech II T-Shirt,Product_Name_Under Armour Women's Ignite PIP VI Slide,Product_Name_Under Armour Women's Ignite Slide,Product_Name_Under Armour Women's Micro G Skulpt Running S,Product_Name_Web Camera,Product_Name_Yakima DoubleDown Ace Hitch Mount 4-Bike Rack,Product_Name_adidas Brazuca 2014 Official Match Ball,Product_Name_adidas Kids' F5 Messi FG Soccer Cleat,Product_Name_adidas Men's F10 Messi TRX FG Soccer Cleat,Product_Name_adidas Men's Germany Black Crest Away Tee,Product_Name_adidas Youth Germany Black/Red Away Match Soc,Product_Name_insta-bed Neverflat Air Mattress,Shipping_Mode_First Class,Shipping_Mode_Same Day,Shipping_Mode_Second Class,Shipping_Mode_Standard Class,Category_Name_Accessories,Category_Name_As Seen on TV!,Category_Name_Baby,Category_Name_Baseball & Softball,Category_Name_Basketball,Category_Name_Books,Category_Name_Boxing & MMA,Category_Name_CDs,Category_Name_Cameras,Category_Name_Camping & Hiking,Category_Name_Cardio Equipment,Category_Name_Children's Clothing,Category_Name_Cleats,Category_Name_Computers,Category_Name_Consumer Electronics,Category_Name_Crafts,Category_Name_DVDs,Category_Name_Electronics,Category_Name_Fishing,Category_Name_Fitness Accessories,Category_Name_Garden,Category_Name_Girls' Apparel,Category_Name_Golf Apparel,Category_Name_Golf Bags & Carts,Category_Name_Golf Balls,Category_Name_Golf Gloves,Category_Name_Golf Shoes,Category_Name_Health and Beauty,Category_Name_Hockey,Category_Name_Hunting & Shooting,Category_Name_Indoor/Outdoor Games,Category_Name_Kids' Golf Clubs,Category_Name_Lacrosse,Category_Name_Men's Clothing,Category_Name_Men's Footwear,Category_Name_Men's Golf Clubs,Category_Name_Music,Category_Name_Pet Supplies,Category_Name_Shop By Sport,Category_Name_Soccer,Category_Name_Sporting Goods,Category_Name_Strength Training,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs,day_of_week_shipping,day_of_week_order,Delivery_Delay
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,20755,2,20755,77202,1360,180517,1360,73,0.500000,1.0,0,0.0,91.250000,314.640015,18.251453,-66.037056,13.110000,0.04,327.750000,0.29,0.159678,314.640015,91.250000,0.159678,2018-01-31,2018-02-03,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Saturday,Saturday,0.500000
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,19492,2,19492,75939,1360,179254,1360,73,0.833333,1.0,1,0.0,-249.089996,311.359985,18.279451,-66.037064,16.389999,0.05,327.750000,-0.80,0.159678,311.359985,-249.089996,0.159678,2018-01-13,2018-01-18,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Thursday,Thursday,0.166667
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,19491,2,19491,75938,1360,179253,1360,73,0.666667,1.0,0,0.0,-247.779999,309.720001,37.292233,-121.881279,18.030001,0.06,327.750000,-0.80,0.159678,309.720001,-247.779999,0.159678,2018-01-13,2018-01-17,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.333333
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,19490,2,19490,75937,1360,179252,1360,73,0.500000,1.0,0,0.0,22.860001,304.809998,34.125946,-118.291016,22.940001,0.07,327.750000,0.08,0.159678,304.809998,22.860001,0.159678,2018-01-13,2018-01-16,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.500000
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,19489,2,19489,75936,1360,179251,1360,73,0.333333,1.0,0,0.0,134.210007,298.250000,18.253769,-66.037048,29.500000,0.09,327.750000,0.45,0.159678,298.250000,134.210007,0.159678,2018-01-13,2018-01-15,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Monday,Monday,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,1005,7,1005,26043,1004,65177,1004,45,0.666667,1.0,0,0.0,40.000000,399.980011,40.640930,-73.942711,0.000000,0.00,399.980011,0.10,0.195975,399.980011,40.000000,0.195975,2016-01-16,2016-01-20,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.333333
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,9141,7,9141,26037,1004,65161,1004,45,0.500000,0.5,1,0.0,-613.770019,395.980011,35.362545,-119.018700,4.000000,0.01,399.980011,-1.55,0.195975,395.980011,-613.770019,0.195975,2016-01-16,2016-01-19,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.000000
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,291,7,291,26024,1004,65129,1004,45,0.833333,1.0,1,0.0,141.110001,391.980011,41.629959,-72.967155,8.000000,0.02,399.980011,0.36,0.195975,391.980011,141.110001,0.195975,2016-01-15,2016-01-20,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.166667
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,2813,7,2813,26022,1004,65126,1004,45,0.500000,1.0,0,0.0,186.229996,387.980011,18.213350,-66.370575,12.000000,0.03,399.980011,0.48,0.195975,387.980011,186.229996,0.195975,2016-01-15,2016-01-18,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Monday,Monday,0.500000
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,7547,7,7547,26018,1004,65113,1004,45,0.666667,1.0,0,0.0,168.949997,383.980011,18.290380,-66.370613,16.000000,0.04,399.980011,0.44,0.195975,383.980011,168.949997,0.195975,2016-01-15,2016-01-19,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.333333

In [102]:
df.to_excel('/Users/gouribenni/Downloads/Feature_Excel.xlsx', index=False)

In [103]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%m/%d/%Y')
df['shipping_date'] = pd.to_datetime(df['shipping_date'], format='%m/%d/%Y')

In [104]:
df['order_processing_days'] = (df['shipping_date'] - df['order_date']).dt.days

In [105]:
df

,Customer_City,Customer_Country,Customer_State,Customer_Street,Market,Order_City,Order_Country,Order_Region,Order_State,Category_Id,Customer_Id,Department_Id,Order_Customer_Id,Order_Id,Order_Item_Cardprod_Id,Order_Item_Id,Product_Card_Id,Product_Category_Id,Days_for_shipping_(real),Days_for_shipment_(scheduled),Late_delivery_risk,Order_Item_Quantity,Benefit_per_order,Sales_per_customer,Latitude,Longitude,Order_Item_Discount,Order_Item_Discount_Rate,Order_Item_Product_Price,Order_Item_Profit_Ratio,Sales,Order_Item_Total,Order_Profit_Per_Order,Product_Price,order_date,shipping_date,Delivery_Status_Advance shipping,Delivery_Status_Late delivery,Delivery_Status_Shipping canceled,Delivery_Status_Shipping on time,Type_CASH,Type_DEBIT,Type_PAYMENT,Type_TRANSFER,Customer_Segment_Consumer,Customer_Segment_Corporate,Customer_Segment_Home Office,Department_Name_Apparel,Department_Name_Book Shop,Department_Name_Discs Shop,Department_Name_Fan Shop,Department_Name_Fitness,Department_Name_Footwear,Department_Name_Golf,Department_Name_Health and Beauty,Department_Name_Outdoors,Department_Name_Pet Shop,Department_Name_Technology,Order_Status_CANCELED,Order_Status_CLOSED,Order_Status_COMPLETE,Order_Status_ON_HOLD,Order_Status_PAYMENT_REVIEW,Order_Status_PENDING,Order_Status_PENDING_PAYMENT,Order_Status_PROCESSING,Order_Status_SUSPECTED_FRAUD,Product_Name_Adult dog supplies,Product_Name_Baby sweater,Product_Name_Bag Boy Beverage Holder,Product_Name_Bag Boy M330 Push Cart,Product_Name_Bowflex SelectTech 1090 Dumbbells,Product_Name_Bridgestone e6 Straight Distance NFL Carolina,Product_Name_Bridgestone e6 Straight Distance NFL San Dieg,Product_Name_Bridgestone e6 Straight Distance NFL Tennesse,Product_Name_Brooks Women's Ghost 6 Running Shoe,Product_Name_Bushnell Pro X7 Jolt Slope Rangefinder,Product_Name_CDs of rock,Product_Name_Children's heaters,Product_Name_Cleveland Golf Collegiate My Custom Wedge 588,Product_Name_Cleveland Golf Women's 588 RTX CB Satin Chrom,Product_Name_Clicgear 8.0 Shoe Brush,Product_Name_Clicgear Rovic Cooler Bag,Product_Name_Columbia Men's PFG Anchor Tough T-Shirt,Product_Name_DVDs,Product_Name_Dell Laptop,Product_Name_Diamondback Boys' Insight 24 Performance Hybr,Product_Name_Diamondback Girls' Clarity 24 Hybrid Bike 201,Product_Name_Diamondback Women's Serene Classic Comfort Bi,Product_Name_ENO Atlas Hammock Straps,Product_Name_Elevation Training Mask 2.0,Product_Name_Field & Stream Sportsman 16 Gun Fire Safe,Product_Name_Fighting video games,Product_Name_First aid kit,Product_Name_Fitbit The One Wireless Activity & Sleep Trac,Product_Name_Garmin Approach S3 Golf GPS Watch,Product_Name_Garmin Approach S4 Golf GPS Watch,Product_Name_Garmin Forerunner 910XT GPS Watch,Product_Name_Glove It Imperial Golf Towel,Product_Name_Glove It Urban Brick Golf Towel,Product_Name_Glove It Women's Imperial Golf Glove,Product_Name_Glove It Women's Mod Oval 3-Zip Carry All Gol,Product_Name_Glove It Women's Mod Oval Golf Glove,Product_Name_GoPro HERO3+ Black Edition Camera,Product_Name_GolfBuddy VT3 GPS Watch,Product_Name_Hirzl Men's Hybrid Golf Glove,Product_Name_Hirzl Women's Hybrid Golf Glove,Product_Name_Hirzl Women's Soffft Flex Golf Glove,Product_Name_Industrial consumer electronics,Product_Name_LIJA Women's Argyle Golf Polo,Product_Name_LIJA Women's Button Golf Dress,Product_Name_LIJA Women's Eyelet Sleeveless Golf Polo,Product_Name_LIJA Women's Mid-Length Panel Golf Shorts,Product_Name_Lawn mower,Product_Name_MDGolf Pittsburgh Penguins Putter,Product_Name_Men's gala suit,Product_Name_Merrell Men's All Out Flash Trail Running Sho,Product_Name_Merrell Women's Grassbow Sport Hiking Shoe,Product_Name_Merrell Women's Grassbow Sport Waterproof Hik,Product_Name_Merrell Women's Siren Mid Waterproof Hiking B,Product_Name_Mio ALPHA Heart Rate Monitor/Sport Watch,Product_Name_Nike Dri-FIT Crew Sock 6 Pack,Product_Name_Nike Kids' Grade School KD VI Basketball Shoe,Product_Name_Nike Men's CJ Elite 2 TD Football Cleat,Product_Name_Nike Men's Comfort 2 Slide,Product_Name_Nike Men's Deutschland Weltmeister Winners Bl,Product_Name_Nike Men's Dri-FIT Victory Golf Polo,Product_Name_Nike Men's Fingertrap Max Training Shoe,Product_Name_Nike Men's Free 5.0+ Running Shoe,Product_Name_Nike Men's Free TR 5.0 TB Training Shoe,Product_Name_Nike Men's Kobe IX Elite Low Basketball Shoe,Product_Name_Nike Women's Free 5.0 TR FIT PRT 4 Training S,Product_Name_Nike Women's Legend V-Neck T-Shirt,Product_Name_Nike Women's Tempo Shorts,Product_Name_O'Brien Men's Neoprene Life Vest,Product_Name_Ogio Race Golf Shoes,Product_Name_Pelican Maverick 100X Kayak,Product_Name_Pelican Sunstream 100 Kayak,Product_Name_Perfect Fitness Perfect Rip Deck,Product_Name_Polar FT4 Heart Rate Monitor,Product_Name_Polar Loop Activity Tracker,Product_Name_Porcelain crafts,Product_Name_Rock music,Product_Name_SOLE E25 Elliptical,Product_Name_SOLE E35 Elliptical,Product_Name_Smart watch,Product_Name_Sports Books,Product_Name_Stiga Master Series ST3100 Competition Indoor,Product_Name_Summer dresses,Product_Name_TYR Boys' Team Digi Jammer,Product_Name_TaylorMade 2014 Purelite Stand Bag,Product_Name_TaylorMade White Smoke IN-12 Putter,Product_Name_TaylorMade Women's RBZ SL Rescue,Product_Name_Team Golf New England Patriots Putter Grip,Product_Name_Team Golf Pittsburgh Steelers Putter Grip,Product_Name_Team Golf San Francisco Giants Putter Grip,Product_Name_Team Golf St. Louis Cardinals Putter Grip,Product_Name_Team Golf Tennessee Volunteers Putter Grip,Product_Name_Team Golf Texas Longhorns Putter Grip,Product_Name_The North Face Women's Recon Backpack,Product_Name_Titleist Club Glove Travel Cover,Product_Name_Titleist Pro V1 High Numbers Personalized Gol,Product_Name_Titleist Pro V1x Golf Balls,Product_Name_Titleist Pro V1x High Numbers Golf Balls,Product_Name_Titleist Pro V1x High Numbers Personalized Go,Product_Name_Titleist Small Wheeled Travel Cover,Product_Name_Top Flite Women's 2014 XL Hybrid,Product_Name_Total Gym 1400,Product_Name_Toys,Product_Name_Under Armour Girls' Toddler Spine Surge Runni,Product_Name_Under Armour Hustle Storm Medium Duffle Bag,Product_Name_Under Armour Kids' Mercenary Slide,Product_Name_Under Armour Men's Compression EV SL Slide,Product_Name_Under Armour Men's Tech II T-Shirt,Product_Name_Under Armour Women's Ignite PIP VI Slide,Product_Name_Under Armour Women's Ignite Slide,Product_Name_Under Armour Women's Micro G Skulpt Running S,Product_Name_Web Camera,Product_Name_Yakima DoubleDown Ace Hitch Mount 4-Bike Rack,Product_Name_adidas Brazuca 2014 Official Match Ball,Product_Name_adidas Kids' F5 Messi FG Soccer Cleat,Product_Name_adidas Men's F10 Messi TRX FG Soccer Cleat,Product_Name_adidas Men's Germany Black Crest Away Tee,Product_Name_adidas Youth Germany Black/Red Away Match Soc,Product_Name_insta-bed Neverflat Air Mattress,Shipping_Mode_First Class,Shipping_Mode_Same Day,Shipping_Mode_Second Class,Shipping_Mode_Standard Class,Category_Name_Accessories,Category_Name_As Seen on TV!,Category_Name_Baby,Category_Name_Baseball & Softball,Category_Name_Basketball,Category_Name_Books,Category_Name_Boxing & MMA,Category_Name_CDs,Category_Name_Cameras,Category_Name_Camping & Hiking,Category_Name_Cardio Equipment,Category_Name_Children's Clothing,Category_Name_Cleats,Category_Name_Computers,Category_Name_Consumer Electronics,Category_Name_Crafts,Category_Name_DVDs,Category_Name_Electronics,Category_Name_Fishing,Category_Name_Fitness Accessories,Category_Name_Garden,Category_Name_Girls' Apparel,Category_Name_Golf Apparel,Category_Name_Golf Bags & Carts,Category_Name_Golf Balls,Category_Name_Golf Gloves,Category_Name_Golf Shoes,Category_Name_Health and Beauty,Category_Name_Hockey,Category_Name_Hunting & Shooting,Category_Name_Indoor/Outdoor Games,Category_Name_Kids' Golf Clubs,Category_Name_Lacrosse,Category_Name_Men's Clothing,Category_Name_Men's Footwear,Category_Name_Men's Golf Clubs,Category_Name_Music,Category_Name_Pet Supplies,Category_Name_Shop By Sport,Category_Name_Soccer,Category_Name_Sporting Goods,Category_Name_Strength Training,Category_Name_Tennis & Racquet,Category_Name_Toys,Category_Name_Trade-In,Category_Name_Video Games,Category_Name_Water Sports,Category_Name_Women's Apparel,Category_Name_Women's Clothing,Category_Name_Women's Golf Clubs,day_of_week_shipping,day_of_week_order,Delivery_Delay,order_processing_days
0,Caguas,Puerto Rico,PR,5365 Noble Nectar Island,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,73,20755,2,20755,77202,1360,180517,1360,73,0.500000,1.0,0,0.0,91.250000,314.640015,18.251453,-66.037056,13.110000,0.04,327.750000,0.29,0.159678,314.640015,91.250000,0.159678,2018-01-31,2018-02-03,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Saturday,Saturday,0.500000,3
1,Caguas,Puerto Rico,PR,2679 Rustic Loop,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,19492,2,19492,75939,1360,179254,1360,73,0.833333,1.0,1,0.0,-249.089996,311.359985,18.279451,-66.037064,16.389999,0.05,327.750000,-0.80,0.159678,311.359985,-249.089996,0.159678,2018-01-13,2018-01-18,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Thursday,Thursday,0.166667,5
2,San Jose,EE. UU.,CA,8510 Round Bear Gate,Pacific Asia,Bikaner,India,South Asia,Rajast√°n,73,19491,2,19491,75938,1360,179253,1360,73,0.666667,1.0,0,0.0,-247.779999,309.720001,37.292233,-121.881279,18.030001,0.06,327.750000,-0.80,0.159678,309.720001,-247.779999,0.159678,2018-01-13,2018-01-17,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.333333,4
3,Los Angeles,EE. UU.,CA,3200 Amber Bend,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,19490,2,19490,75937,1360,179252,1360,73,0.500000,1.0,0,0.0,22.860001,304.809998,34.125946,-118.291016,22.940001,0.07,327.750000,0.08,0.159678,304.809998,22.860001,0.159678,2018-01-13,2018-01-16,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.500000,3
4,Caguas,Puerto Rico,PR,8671 Iron Anchor Corners,Pacific Asia,Townsville,Australia,Oceania,Queensland,73,19489,2,19489,75936,1360,179251,1360,73,0.333333,1.0,0,0.0,134.210007,298.250000,18.253769,-66.037048,29.500000,0.09,327.750000,0.45,0.159678,298.250000,134.210007,0.159678,2018-01-13,2018-01-15,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,Monday,Monday,0.666667,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,Brooklyn,EE. UU.,NY,1322 Broad Glade,Pacific Asia,Shangh√°i,China,Eastern Asia,Shangh√°i,45,1005,7,1005,26043,1004,65177,1004,45,0.666667,1.0,0,0.0,40.000000,399.980011,40.640930,-73.942711,0.000000,0.00,399.980011,0.10,0.195975,399.980011,40.000000,0.195975,2016-01-16,2016-01-20,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.333333,4
180515,Bakersfield,EE. UU.,CA,7330 Broad Apple Moor,Pacific Asia,Hirakata,Jap√≥n,Eastern Asia,Osaka,45,9141,7,9141,26037,1004,65161,1004,45,0.500000,0.5,1,0.0,-613.770019,395.980011,35.362545,-119.018700,4.000000,0.01,399.980011,-1.55,0.195975,395.980011,-613.770019,0.195975,2016-01-16,2016-01-19,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.000000,3
180516,Bristol,EE. UU.,CT,97 Burning Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,291,7,291,26024,1004,65129,1004,45,0.833333,1.0,1,0.0,141.110001,391.980011,41.629959,-72.967155,8.000000,0.02,399.980011,0.36,0.195975,391.980011,141.110001,0.195975,2016-01-15,2016-01-20,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Wednesday,Wednesday,0.166667,5
180517,Caguas,Puerto Rico,PR,2585 Silent Autumn Landing,Pacific Asia,Adelaide,Australia,Oceania,Australia del Sur,45,2813,7,2813,26022,1004,65126,1004,45,0.500000,1.0,0,0.0,186.229996,387.980011,18.213350,-66.370575,12.000000,0.03,399.980011,0.48,0.195975,387.980011,186.229996,0.195975,2016-01-15,2016-01-18,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Monday,Monday,0.500000,3
180518,Caguas,Puerto Rico,PR,697 Little Meadow,Pacific Asia,Nagercoil,India,South Asia,Tamil Nadu,45,7547,7,7547,26018,1004,65113,1004,45,0.666667,1.0,0,0.0,168.949997,383.980011,18.290380,-66.370613,16.000000,0.04,399.980011,0.44,0.195975,383.980011,168.949997,0.195975,2016-01-15,2016-01-19,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tuesday,Tuesday,0.333333,4

In [106]:
df.dtypes

Customer_City                        object
Customer_Country                     object
Customer_State                       object
Customer_Street                      object
Market                               object
                                     ...
Category_Name_Women's Golf Clubs      uint8
day_of_week_shipping                 object
day_of_week_order                    object
Delivery_Delay                      float64
order_processing_days                 int64
Length: 243, dtype: object

In [108]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [113]:
X = df[['Shipping_Mode_First Class', 'Shipping_Mode_Same Day', 'Shipping_Mode_Second Class', 
        'Shipping_Mode_Standard Class', 'Order_Status_SUSPECTED_FRAUD', 'Order_Status_PROCESSING', 
        'Order_Status_PENDING_PAYMENT', 'Order_Status_PENDING', 'Order_Status_PAYMENT_REVIEW', 
        'Order_Status_ON_HOLD', 'Order_Status_COMPLETE', 'Order_Status_CLOSED','Order_Status_CANCELED', 
        'Delivery_Status_Advance shipping', 'Delivery_Status_Shipping on time', 'Delivery_Status_Shipping canceled',
       'Delivery_Status_Late delivery']]
y = df['Delivery_Delay']

In [115]:


X = df[['Shipping_Mode_First Class', 'Shipping_Mode_Same Day', 'Shipping_Mode_Second Class', 
        'Shipping_Mode_Standard Class', 'Order_Status_SUSPECTED_FRAUD', 'Order_Status_PROCESSING', 
        'Order_Status_PENDING_PAYMENT', 'Order_Status_PENDING', 'Order_Status_PAYMENT_REVIEW', 
        'Order_Status_ON_HOLD', 'Order_Status_COMPLETE', 'Order_Status_CLOSED','Order_Status_CANCELED', 
        'Delivery_Status_Advance shipping', 'Delivery_Status_Shipping on time', 'Delivery_Status_Shipping canceled',
       'Delivery_Status_Late delivery']]
y = df['Delivery_Delay']
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

# Print the shape of each dataset
print('For Input Features')
print('Training set shape:', X_train.shape)
print('Validation set shape:', X_val.shape)
print('Test set shape:', X_test.shape)

For Input Features
Training set shape: (108311, 17)
Validation set shape: (36104, 17)
Test set shape: (36104, 17)

In [137]:
from sklearn.metrics import r2_score

rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the model on the training set
rf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf.predict(X_test)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Print the R-squared score
print("R-squared score:", r2)

print("MSE", mse)
print("MAE", mae)

R-squared score: 0.892437166755578
MSE 0.010192293570280436
MAE 0.06976327346751705

In [120]:
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the SVR model
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

# Fit the model on the training set
svr.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svr.predict(X_test)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

# Print the R-squared score
print("R-squared score:", r2)

R-squared score: 0.8697274117416021

In [136]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the KNN model
model = KNeighborsRegressor(n_neighbors=5)

# Fit the model on the training set
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Print the R-squared score
print("R-squared score:", r2)

print("MSE", mse)
print("MAE", mae)

R-squared score: 0.8581363493354156
MSE 0.01344252406627767
MAE 0.07254413176748654

In [135]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Assuming you already have the X and y defined as per your previous question

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the XGBoost model
model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Fit the model on the training set
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

# Print the R-squared score
print("")
print("R-squared score:", r2)

R-squared score: 0.8924406686237678
MSE 0.010192994544682782
MAE 0.06976794476102038

In [126]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-1.7.5-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (1.8 MB)
Requirement already satisfied: numpy in /Users/gouribenni/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /Users/gouribenni/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)
Installing collected packages: xgboost
Successfully installed xgboost-1.7.5
Note: you may need to restart the kernel to use updated packages.

In [134]:
import xgboost as xgb
from sklearn.metrics import r2_score

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the XGBoost regressor model
xgb_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

# Fit the model on the training set
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(X_test)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Print the R-squared score
print("XGBOOST")
print("R-squared score:", r2)

print("MSE", mse)
print("MAE", mae)

XGBOOST
R-squared score: 0.8924297691279265
MSE 0.010192994544682782
MAE 0.06976794476102038